apiVersion: v1
kind: Service
metadata:
  name: ecr-registry
  namespace: sage
  labels:
    app: ecr-registry
spec:
  selector:
    k8s-app: ecr-registry
  type: ClusterIP
  ports:
  - name: ecr-registry
    port: 80
    protocol: TCP
    targetPort: 5000