version: '3.7'

# to start this enviornment with a jenkins instance, use run.sh instead of this docker-compose file directly



services:

  sage-ecr:
    image: sagecontinuum/sage-ecr:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}:/usr/src/app  # for development only
    restart: always
    env_file: mysql.env
    networks:
      - sage-ecr
    environment:
      AUTH_METHOD: ${AUTH_METHOD}
      tokenInfoEndpoint: ${SageTokenInfoEndpoint} 
      tokenInfoUser: ${SageTokenInfoUser}  
      tokenInfoPassword: ${SageTokenInfoPassword}
      JENKINS_SERVER: ${JENKINS_SERVER}
      JENKINS_USER: ${JENKINS_USER}
      JENKINS_TOKEN: ${JENKINS_TOKEN}
      DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
    


  db:
    image: mysql:8.0.20
    env_file: mysql.env
    volumes:
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - sage-ecr-db:/var/lib/mysql
    networks:
      - sage-ecr

  registry.local:
    restart: always
    image: registry:2
    ports:
      - 5001:5000
    networks:
      - sage-ecr

volumes:
  sage-ecr-db:
  
    
networks:
  sage-ecr:
   name: sage-ecr

