
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecr-jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - http:
      paths:
      - path: /ecr/jenkins/
        pathType: Prefix
        backend:
          service:
            name: ecr-jenkins
            port:
              number: 8080

