apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base/ # relative path to the base folder

resources:
  - ecr-api.yaml
  - ecr-jenkins.yaml

secretGenerator:
  - name: ecr-jenkins-casc-secret
    files:
      - casc_jenkins.yaml